from typing import List, Any


class BeautifulSoup:
    def __init__(self, text : str, parser_type: str) -> None: ...
    def findAll(self, tag: str) -> List[Any]: ...

    @property
    def body(self) -> BeautifulSoup: ...
    ...

