git:
  submodules: true

language: python

python:
  - "3.6"

cache: pip3

install:
  - pip3 install -r requirements.txt
  - pip3 install pylint

before_script:
  - cd Nduja
  - export MYPYPATH=$(pwd)/.stub:$(pwd):$(pwd)/../typeshed
  

script:
  - mypy --python-version 3.6 address_checkers/*.py
  - mypy --python-version 3.6 dao/*.py
  - mypy --python-version 3.6 db/*.py
  - mypy --python-version 3.6 result_parser/*.py
  - mypy --python-version 3.6 user_info_retriever/*.py
  - mypy --python-version 3.6 utility/*.py
  - mypy --python-version 3.6 wallet_collectors/*.py
  - mypy --python-version 3.6 __main__.py
  - mypy --python-version 3.6 graph/*.py
  - pylint -d "C" -d "R" -d "W" address_checkers/*.py
  - pylint -d "C" -d "R" -d "W" dao/*.py
  - pylint -d "C" -d "R" -d "W" db/*.py
  - pylint -d "C" -d "R" -d "W" result_parser/*.py
  - pylint -d "C" -d "R" -d "W" user_info_retriever/*.py
  - pylint -d "C" -d "R" -d "W" utility/*.py
  - pylint -d "C" -d "R" -d "W" wallet_collectors/*.py
  - pylint -d "C" -d "R" -d "W" __main__.py
  - pylint -d "C" -d "R" -d "W" graph/*.py
