language: python

python:
  - "3.6"

cache: pip

install:
  - pip install -r requirements.txt

before_script:
  - git clone https://github.com/python/typeshed.git
  - export MYPYPATH=$(pwd)/.stub:$(pwd):$(pwd)/typeshed

script:
  - mypy --python-version 3.6 --cache-dir /tmp/mypy address_checkers/*.py
  - mypy --python-version 3.6 --cache-dir /tmp/mypy dao/*.py
  - mypy --python-version 3.6 --cache-dir /tmp/mypy db/*.py
  - mypy --python-version 3.6 --cache-dir /tmp/mypy result_parser/*.py
  - mypy --python-version 3.6 --cache-dir /tmp/mypy user_info_retriever/*.py
  - mypy --python-version 3.6 --cache-dir /tmp/mypy utility/*.py
  - mypy --python-version 3.6 --cache-dir /tmp/mypy wallet_collectors/*.py
  - mypy --python-version 3.6 --cache-dir /tmp/mypy __main__.py