from typing import Optional, Any, Dict


class JSONRPCException(Exception): ...

HTTP_TIMEOUT = 30 # type: int


# object in class declaration to be coherent with python2 and the real
# implementation
class AuthServiceProxy(object):
    def __init__(self,
                 service_url : str,
                 service_name: Optional[str] = None,
                 timeout: int = HTTP_TIMEOUT,
                 connection: Optional[Any] = None) -> None: ...

    def getblockcount(self) -> int: ...

    def get_block(self, hash: str) -> Dict: ...

    def get_block_hash(self, blocknumber: int) -> str: ...

    def stop(self): ...

    def importaddress(self, wallet: str, label: str, read_only: bool) \
            -> None: ...

    def getinfo(self): ...

    def getrawtransaction(self, txhash: str) -> Any: ...

    def decoderawtransaction(self, transaction: Any) -> dict: ...

    def getblock(self, blockhash: str) -> dict: ...

    def getblockhash(self, blocknumber: int) -> str: ...